language: dart

dart:
  - stable

cache:
  directories:
    - $HOME/.pub-cache

jobs:
  include:
    - stage: build and deploy
      if: branch = main
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - lib32stdc++6
      before_script:
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - export PATH="$PATH:`pwd`/flutter/bin"
        - flutter doctor
      script:
        - flutter pub get
        - flutter build apk
        - pwd && cd build && ls
      deploy:
        provider: script
        script: curl -sL https://raw.githubusercontent.com/jakejarvis/s3-sync-action/master/src/main.js | node -- --args="--acl public-read" --source-dir=build/app/outputs/flutter-apk/app-release.apk --bucket=app-nelson1234 --region=us-east-1 --destination-dir=/
        skip_cleanup: true
        on:
          branch: main
