os: osx
language: generic

before_install:
- brew update
- brew install --HEAD usbmuxd
- brew unlink usbmuxd
- brew link usbmuxd
- brew install ideviceinstaller
- brew install ios-deploy
- brew install cocoapods

install:
- git clone https://github.com/flutter/flutter.git -b stable
- export PATH=`pwd`/flutter/bin:$PATH
- flutter doctor

script:
- flutter build ios --release --no-codesign

deploy:
- provider: script
  skip_cleanup: true
  script: >
    brew install awscli &&
    aws s3 sync /Users/travis/build/okoye-nelson/flutter_app/build/ios/iphoneos/ s3://app-nelson1234/ --acl public-read --delete &&
    rm -rf ~/Library/Developer/Xcode/DerivedData/
  on:
    branch: main