name: Build and Deploy iOS App

on:
  push:
    branches: main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: set up flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build iOS App
      run: flutter build ios --release --no-codesign

    #  - name: Upload to S3
    #   uses: jonfriesen/s3-put-action@v1.0.0
    #   with:
    #     args: --acl-public
    #   env:
    #     LOCAL_FILE: /Users/runner/work/flutter_app/flutter_app/build/ios/iphoneos/Runner.app
    #     REMOTE_FILE: /
    #     AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
    #     AWS_BUCKET: app-nelson1234
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Upload to S3
      uses: nelsonomuto/s3-sync-action@v2.0.0
      with:
        args: --acl-public
      env:
        LOCAL_FILE: /Users/runner/work/flutter_app/flutter_app/build/ios/iphoneos/Runner.app
        REMOTE_FILE: /
        AWS_BUCKET: app-nelson1234